from __future__ import annotations

from xinyu_text_variants import readable_markers


OWNER_DIRECT_CODEX_DELEGATE_MARKERS = (
    "用codex",
    "调用codex",
    "让codex",
    "交给codex",
    "找codex",
    "codex搜索",
    "codex查",
    "codex浏览",
    "codex联网",
    "codex学习",
    "codex研究",
)
OWNER_DIRECT_CODEX_SUPPORT_MARKERS = (
    "联网",
    "浏览网络",
    "搜索",
    "查一下",
    "查资料",
    "找资料",
    "学习",
    "研究",
    "想不通",
    "没办法",
    "自己想办法",
)
OWNER_DIRECT_CODEX_NEGATIVE_MARKERS = (
    "别用codex",
    "不要用codex",
    "不用codex",
    "先别用codex",
    "别调用codex",
    "不要调用codex",
    "没让你用codex",
    "没有让你用codex",
    "不是让你用codex",
    "不是叫你用codex",
    "不是提到codex",
    "不是说codex",
    "一提codex",
    "提到codex就",
    "自动开codex",
    "自动启动codex",
)
OWNER_SELF_CODE_EDIT_GRANT_MARKERS = (
    "改你的代码",
    "更改你的代码",
    "修改你的代码",
    "改动你的代码",
    "改自己的代码",
    "修改自己的代码",
    "主动改代码",
    "主动尝试更改你的代码",
    "对你的代码进行改动",
    "改项目代码",
    "自我代码迭代",
    "自己动代码",
    "自己改项目",
    "主动修改代码",
    "主动更改代码",
    *readable_markers(
        "改你的代码",
        "修改你的代码",
        "更改你的代码",
        "改自己的代码",
        "修改自己的代码",
        "修改自身代码",
        "主动修改代码",
        "主动改代码",
        "自改代码",
        "自我代码修改",
        "自身代码",
        "所有代码",
        "modify your code",
        "edit your code",
        "change your own code",
        "code modification ability",
        "self-modification ability",
        "self editing ability",
        "your own code modification ability",
        "代码修改能力",
        "自改能力",
        "自我修改能力",
        "自己的代码修改能力",
        "self-code",
    ),
)
OWNER_SELF_CODE_START_MARKERS = (
    "现在开始",
    "现在就开始",
    "可以现在开始",
    "可以现在就开始",
    "可以开始",
    "开始吧",
    "开始动手",
    "开始改",
    "直接开始",
    "那就开始",
    "权限给",
    "权限低",
    *readable_markers(
        "现在开始",
        "现在就开始",
        "开始吧",
        "开始改",
        "直接开始",
        "进行修改",
        "现在修改",
        "现在主动修改",
        "start now",
        "go ahead",
        "proceed",
        "make it stronger",
        "strengthen it",
        "improve it",
        "加强一下",
        "增强一下",
        "提升一下",
        "补强一下",
        "修一下",
    ),
)
OWNER_SELF_CODE_NEGATIVE_MARKERS = (
    "别改代码",
    "不要改代码",
    "先别改代码",
    "先别改",
    "别动代码",
    "不要动代码",
    *readable_markers(
        "别改代码",
        "不要改代码",
        "先别改代码",
        "别动代码",
        "不要动代码",
        "不要修改",
        "先别修改",
        "do not edit",
        "don't edit",
        "no code changes",
    ),
)
OWNER_SELF_CODE_GRANT_CUES = (
    "允许",
    "可以",
    "授权",
    "同意",
    "准许",
    "支持",
    "试试",
    "动手",
    "开始",
    "直接",
    "去",
    "给你",
    "都可以",
    "吧",
    *readable_markers(
        "允许",
        "授权",
        "同意",
        "可以",
        "要求",
        "请",
        "希望",
        "现在",
        "开始",
        "直接",
        "进行",
        "动手",
        "go ahead",
        "approved",
        "approve",
        "authorized",
        "please",
        "weak",
        "stronger",
        "improve",
        "strengthen",
        "弱",
        "不够强",
        "不太行",
        "加强",
        "增强",
        "提升",
        "补强",
    ),
)


__all__ = (
    "OWNER_DIRECT_CODEX_DELEGATE_MARKERS",
    "OWNER_DIRECT_CODEX_SUPPORT_MARKERS",
    "OWNER_DIRECT_CODEX_NEGATIVE_MARKERS",
    "OWNER_SELF_CODE_EDIT_GRANT_MARKERS",
    "OWNER_SELF_CODE_START_MARKERS",
    "OWNER_SELF_CODE_NEGATIVE_MARKERS",
    "OWNER_SELF_CODE_GRANT_CUES",
)
