from __future__ import annotations

from xinyu_bridge_autonomous_note_dispatch import (
    append_autonomous_outcome_shadow_notes,
    append_autonomous_outward_note,
    append_creative_writing_note,
    append_daily_digest_note,
    append_emotion_council_note,
    append_github_learning_note,
    append_goal_ecology_note,
    append_goal_outcome_observer_note,
    append_goldmark_dehydrate_note,
    append_impulse_soup_note,
    append_initiative_spine_note,
    append_learning_closed_loop_self_thought_note,
    append_proactive_request_note,
    append_proactivity_shadow_note,
    append_review_inbox_note,
    append_self_action_gateway_note,
    append_self_action_patch_executor_note,
    append_self_exploration_note,
    append_self_thought_loop_note,
    append_self_thought_research_notes,
    append_watched_source_note,
    run_autonomous_self_thought_sidecars,
)
from xinyu_bridge_autonomous_proactive_ready_note import append_desktop_proactive_candidate_ready_note


__all__ = (
    "run_autonomous_self_thought_sidecars",
    "append_watched_source_note",
    "append_github_learning_note",
    "append_daily_digest_note",
    "append_creative_writing_note",
    "append_review_inbox_note",
    "append_goldmark_dehydrate_note",
    "append_goal_ecology_note",
    "append_self_action_gateway_note",
    "append_self_action_patch_executor_note",
    "append_self_thought_loop_note",
    "append_proactive_request_note",
    "append_self_exploration_note",
    "append_learning_closed_loop_self_thought_note",
    "append_self_thought_research_notes",
    "append_desktop_proactive_candidate_ready_note",
    "append_autonomous_outcome_shadow_notes",
    "append_autonomous_outward_note",
    "append_goal_outcome_observer_note",
    "append_proactivity_shadow_note",
    "append_emotion_council_note",
    "append_impulse_soup_note",
    "append_initiative_spine_note",
)
