from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class ServiceBoundaryContract:
    service_id: str
    local_owner: str
    owner_layer: str
    purpose: str
    api_routes: tuple[str, ...]
    runtime_facade_methods: tuple[str, ...]
    contract_modules: tuple[str, ...]
    validation_tests: tuple[str, ...]
    process_split_candidate: bool
    process_split_ready: bool
    process_split_gate: str
    process_adapter_kind: str = "local_only"


SERVICEIZATION_PLAN_REL = "D:/XinYu/docs/plans/XINYU-SERVICEIZATION-PLAN-2026-06-08.md"

PROTECTED_PROCESS_SPLIT_MODULES = (
    "xinyu_bridge_slow_live_turn.py",
    "xinyu_bridge_codex_runtime.py",
    "xinyu_bridge_codex_policy_markers.py",
    "xinyu_bridge_semantic_fast_pipeline.py",
)

SERVICE_BOUNDARY_CONTRACTS = (
    ServiceBoundaryContract(
        service_id="chat_turn",
        local_owner="ChatService + BridgeRuntimeAdapter",
        owner_layer="application_service/runtime",
        purpose="Normalize /chat requests, preserve turn execution, and keep the main slow-live runtime local.",
        api_routes=(
            "/chat",
            "/internal/message/ack",
            "/internal/message/drop",
            "/turn/cancel",
            "/turn/retry-lightweight",
            "/turn/skip-sidecar",
            "/turn/continue",
            "/turn/status-message",
        ),
        runtime_facade_methods=(
            "chat",
            "message_ack",
            "message_drop",
            "turn_cancel",
            "turn_retry_lightweight",
            "turn_skip_sidecar",
            "turn_continue",
            "turn_status_message",
        ),
        contract_modules=(
            "xinyu_bridge_chat_turn_contract.py",
            "xinyu_bridge_chat_turn_service.py",
            "xinyu_chat_service.py",
            "services/chat_service.py",
            "xinyu_bridge_chat_turn.py",
            "xinyu_bridge_turn_pipeline.py",
            "xinyu_bridge_slow_live_turn.py",
            "xinyu_bridge_intervention_routes.py",
            "xinyu_bridge_utility_message.py",
            "xinyu_bridge_utility_routes.py",
        ),
        validation_tests=(
            "tests/test_chat_turn_contract.py",
            "tests/test_chat_turn_service.py",
            "tests/test_bridge_chat_turn.py",
            "tests/test_bridge_slow_live_turn.py",
            "tests/test_turn_intervention_routes.py",
            "tests/test_bridge_utility_routes.py",
            "tests/test_unsent_reply_retraction.py",
            "tests/test_action_feedback_surface.py",
            "tests/smoke/initiative/chat_service_smoke.py",
        ),
        process_split_candidate=False,
        process_split_ready=False,
        process_split_gate="Main chat runtime, persona, memory, and proactive policy remain local until API/runtime seams are stable.",
    ),
    ServiceBoundaryContract(
        service_id="proactive_delivery",
        local_owner="ProactiveService + QQOutboxService",
        owner_layer="application_service/api",
        purpose="Own proactive claim, ack, desktop approval, and QQ outbox lifecycle contracts.",
        api_routes=(
            "/proactive",
            "/proactive/ack",
            "/desktop/proactive/ack",
            "/qq/outbox/claim",
            "/qq/outbox/ack",
        ),
        runtime_facade_methods=(
            "proactive",
            "proactive_ack",
            "desktop_proactive_ack",
            "qq_outbox_claim",
            "qq_outbox_claim_fast",
            "qq_outbox_ack",
            "qq_outbox_ack_fast",
        ),
        contract_modules=(
            "xinyu_bridge_proactive_delivery_contract.py",
            "xinyu_bridge_proactive_delivery_route_backend.py",
            "xinyu_bridge_proactive_delivery_worker_service.py",
            "xinyu_bridge_proactive_delivery_state_store.py",
            "xinyu_bridge_proactive_delivery_routes.py",
            "xinyu_bridge_proactive_delivery_claim.py",
            "xinyu_bridge_desktop_proactive_routes.py",
            "xinyu_qq_outbox.py",
            "xinyu_qq_outbox_dispatcher.py",
            "xinyu_autonomy_canary_report.py",
            "xinyu_proactive_response_diagnostics.py",
            "xinyu_proactive_lifecycle_trace.py",
        ),
        validation_tests=(
            "tests/test_proactive_delivery_contract.py",
            "tests/test_proactive_delivery_service.py",
            "tests/test_proactive_delivery_route_backend.py",
            "tests/test_proactive_delivery_worker_service.py",
            "tests/test_proactive_delivery_state_store.py",
            "tests/test_bridge_proactive_outbox_share_gate.py",
            "tests/test_proactive_response_diagnostics.py",
            "tests/test_autonomy_canary_report_store.py",
            "tests/test_proactive_lifecycle_trace_store.py",
            "tests/smoke/bridge/proactive_delivery_route_backend_selection_smoke.py",
            "tests/smoke/bridge/proactive_delivery_worker_service_smoke.py",
            "tests/smoke/qq/qq_outbox_route_alias_smoke.py",
        ),
        process_split_candidate=True,
        process_split_ready=True,
        process_split_gate=(
            "Ready for a controlled proactive_delivery split using route backend selection, terminal ack "
            "idempotency, and local state-store ownership."
        ),
        process_adapter_kind="route_backend",
    ),
    ServiceBoundaryContract(
        service_id="desktop_surface",
        local_owner="DesktopService",
        owner_layer="ui/api",
        purpose="Expose owner-visible desktop snapshots, event stream state, and self-action controls through API contracts.",
        api_routes=(
            "/desktop/snapshot",
            "/desktop/events/recent",
            "/desktop/proactive/inbox",
            "/desktop/chat/recent",
            "/desktop/memory/recent",
            "/desktop/memory/growth-candidates",
            "/desktop/self-action/approval",
        ),
        runtime_facade_methods=(
            "desktop_snapshot",
            "desktop_events_recent",
            "desktop_proactive_inbox",
            "desktop_chat_recent",
            "desktop_memory_recent",
            "desktop_memory_growth_candidates",
            "desktop_self_action_approval",
        ),
        contract_modules=(
            "xinyu_desktop_service.py",
            "xinyu_bridge_desktop_surface_contract.py",
            "xinyu_bridge_desktop_surface_route_backend.py",
            "xinyu_bridge_desktop_surface_worker_service.py",
            "xinyu_bridge_desktop_surface_projection_backend.py",
            "xinyu_bridge_desktop_surface_state_store.py",
            "xinyu_bridge_desktop_surface_snapshot_state_backend.py",
            "xinyu_desktop_events.py",
            "xinyu_desktop_ws.py",
            "xinyu_bridge_desktop_snapshot.py",
            "xinyu_bridge_desktop_events.py",
            "xinyu_bridge_desktop_self_action_approval_backend.py",
            "xinyu_bridge_desktop_self_action_routes.py",
            "xinyu_bridge_desktop_proactive_routes.py",
        ),
        validation_tests=(
            "tests/test_desktop_surface_contract.py",
            "tests/test_desktop_surface_service.py",
            "tests/test_desktop_surface_route_backend.py",
            "tests/test_desktop_surface_worker_service.py",
            "tests/test_desktop_surface_projection_backend.py",
            "tests/test_desktop_surface_state_store.py",
            "tests/test_desktop_surface_snapshot_state_backend.py",
            "tests/test_desktop_self_action_approval_backend.py",
            "tests/test_desktop_event_stream_contract.py",
            "tests/test_bridge_desktop_snapshot.py",
            "tests/test_desktop_self_action_snapshot.py",
            "tests/smoke/bridge/desktop_surface_route_backend_selection_smoke.py",
            "tests/smoke/bridge/desktop_surface_worker_service_smoke.py",
            "tests/smoke/desktop/xinyu_desktop_rest_smoke.py",
        ),
        process_split_candidate=True,
        process_split_ready=True,
        process_split_gate=(
            "Ready for a controlled desktop_surface split using route, projection, approval, "
            "snapshot-state, and local state-store seams."
        ),
        process_adapter_kind="route_backend",
    ),
    ServiceBoundaryContract(
        service_id="desktop_event_stream",
        local_owner="DesktopService.EventStream",
        owner_layer="ui/event_transport",
        purpose="Own desktop event bus replay, websocket lifecycle, backpressure, and degraded fallback.",
        api_routes=("/desktop/events/recent",),
        runtime_facade_methods=("desktop_events_recent",),
        contract_modules=(
            "xinyu_bridge_desktop_surface_contract.py",
            "xinyu_desktop_events.py",
            "xinyu_desktop_ws.py",
            "xinyu_bridge_desktop_events.py",
            "xinyu_bridge_desktop_event_routes.py",
        ),
        validation_tests=(
            "tests/test_desktop_event_stream_contract.py",
            "tests/test_desktop_surface_contract.py",
            "tests/smoke/desktop/xinyu_desktop_rest_smoke.py",
        ),
        process_split_candidate=True,
        process_split_ready=True,
        process_split_gate="Ready for a controlled desktop_event_stream process split; desktop_surface projections remain in-process.",
        process_adapter_kind="ws_contract_only",
    ),
    ServiceBoundaryContract(
        service_id="codex_execution",
        local_owner="CodexService + CodexRunner",
        owner_layer="execution/application_service",
        purpose="Own Codex execution, delegate finalization, completion outbox, and self-code safeguards.",
        api_routes=("/codex/execute",),
        runtime_facade_methods=("codex_execute",),
        contract_modules=(
            "xinyu_codex_service.py",
            "xinyu_bridge_codex_runtime.py",
            "xinyu_bridge_codex_execution_contract.py",
            "xinyu_bridge_codex_execution_backend.py",
            "xinyu_bridge_codex_execution_worker_client.py",
            "xinyu_bridge_codex_execution_worker_service.py",
            "xinyu_bridge_codex_execution_service.py",
            "xinyu_bridge_codex_execution.py",
            "xinyu_bridge_codex_finalization.py",
        ),
        validation_tests=(
            "tests/test_codex_execution_backend.py",
            "tests/test_codex_execution_worker_client.py",
            "tests/test_codex_execution_worker_service.py",
            "tests/test_codex_execution_service.py",
            "tests/test_codex_execution_contract.py",
            "tests/test_bridge_codex_runtime.py",
            "tests/smoke/codex/codex_delegate_smoke.py",
            "tests/smoke/codex/codex_completion_outbox_smoke.py",
            "tests/smoke/codex/codex_execution_worker_rollback_smoke.py",
            "tests/smoke/codex/codex_execution_worker_service_smoke.py",
            "tests/smoke/codex/codex_execution_facade_payload_smoke.py",
            "tests/smoke/codex/codex_execution_service_lifecycle_smoke.py",
        ),
        process_split_candidate=True,
        process_split_ready=True,
        process_split_gate=(
            "Ready for a controlled codex_execution worker boundary using runtime backend rollback and facade "
            "payload contract smokes."
        ),
        process_adapter_kind="worker_client",
    ),
    ServiceBoundaryContract(
        service_id="learning_ingest",
        local_owner="LearningService",
        owner_layer="application_service",
        purpose="Own learning ingest, study, observe, and Codex learning sidecar entry contracts.",
        api_routes=(
            "/learning/ingest",
            "/learning/study",
            "/learning/observe",
            "/sticker/import",
        ),
        runtime_facade_methods=(
            "learning_ingest",
            "learning_study",
            "learning_observe",
            "sticker_import",
        ),
        contract_modules=(
            "xinyu_bridge_learning_ingest_contract.py",
            "xinyu_bridge_learning_ingest_route_backend.py",
            "xinyu_learning_service.py",
            "xinyu_bridge_learning_routes.py",
            "xinyu_bridge_learning_runtime.py",
            "xinyu_bridge_learning_sidecars.py",
            "xinyu_bridge_observation_reports.py",
            "xinyu_bridge_learning_codex_reports.py",
            "xinyu_bridge_utility_sticker.py",
            "xinyu_bridge_utility_routes.py",
            "xinyu_sticker_import.py",
        ),
        validation_tests=(
            "tests/test_learning_ingest_contract.py",
            "tests/test_learning_ingest_service.py",
            "tests/test_learning_ingest_route_backend.py",
            "tests/test_learning_observe_paths.py",
            "tests/test_bridge_observation_reports_store.py",
            "tests/test_bridge_learning_codex_reports.py",
            "tests/test_bridge_utility_routes.py",
            "tests/smoke/tools/xinyu_sticker_import_smoke.py",
            "tests/smoke/bridge/integration/bridge_learning_ingest_smoke.py",
        ),
        process_split_candidate=False,
        process_split_ready=False,
        process_split_gate="Learning remains local until state writes and reviewed-memory gates are fully owned by stores.",
    ),
    ServiceBoundaryContract(
        service_id="external_action",
        local_owner="ActionService + ExternalPluginService + PrivateDesktopService",
        owner_layer="execution/api",
        purpose="Own approved external calls, package install, private ecosystem, browser, and private desktop execution seams.",
        api_routes=(
            "/external/plugins",
            "/external/call",
            "/external/plugins/config",
            "/external/plugins/install",
            "/package/install",
            "/desktop/private-ecosystem/snapshot",
            "/desktop/private-ecosystem/pause",
            "/desktop/private-ecosystem/grant",
            "/desktop/private-ecosystem/tick",
            "/desktop/private-browser/snapshot",
            "/desktop/private-browser/action",
            "/desktop/private-desktop/snapshot",
            "/desktop/private-desktop/live-state",
            "/desktop/private-desktop/frame",
            "/desktop/private-desktop/observe",
            "/desktop/private-desktop/start",
            "/desktop/private-desktop/stop",
        ),
        runtime_facade_methods=(
            "external_plugin_manifest",
            "external_plugin_call",
            "external_plugin_config",
            "external_plugin_install",
            "package_install",
            "desktop_private_ecosystem_snapshot",
            "desktop_private_ecosystem_pause",
            "desktop_private_ecosystem_grant",
            "desktop_private_ecosystem_tick",
            "desktop_private_browser_snapshot",
            "desktop_private_browser_action",
            "desktop_private_desktop_snapshot",
            "desktop_private_desktop_live_state",
            "desktop_private_desktop_frame",
            "desktop_private_desktop_observe",
            "desktop_private_desktop_start",
            "desktop_private_desktop_stop",
        ),
        contract_modules=(
            "xinyu_bridge_external_action_contract.py",
            "xinyu_bridge_external_action_backend.py",
            "xinyu_bridge_external_action_worker_service.py",
            "xinyu_bridge_external_action_route_backend.py",
            "xinyu_bridge_external_plugin_routes.py",
            "xinyu_bridge_action_routes.py",
            "xinyu_bridge_private_ecosystem_routes.py",
            "xinyu_bridge_private_desktop_routes.py",
            "xinyu_private_desktop_service.py",
            "xinyu_private_ecosystem.py",
        ),
        validation_tests=(
            "tests/test_external_action_backend.py",
            "tests/test_external_action_worker_service.py",
            "tests/test_external_action_contract.py",
            "tests/test_external_action_service.py",
            "tests/test_external_action_route_backend.py",
            "tests/test_bridge_external_plugin_routes.py",
            "tests/test_action_status_reply.py",
            "tests/test_desktop_private_ecosystem_snapshot.py",
            "tests/smoke/bridge/external_action_backend_rollback_smoke.py",
            "tests/smoke/bridge/external_action_execution_boundary_smoke.py",
            "tests/smoke/bridge/external_action_route_backend_selection_smoke.py",
            "tests/smoke/bridge/external_action_worker_service_smoke.py",
        ),
        process_split_candidate=True,
        process_split_ready=True,
        process_split_gate=(
            "Ready for a controlled external_action process split using route backend selection and runtime attr rollback."
        ),
        process_adapter_kind="execution_backend",
    ),
    ServiceBoundaryContract(
        service_id="life_metabolism",
        local_owner="LifeMetabolismService",
        owner_layer="application_service/policy",
        purpose="Own self-choice metabolism ticket list/get/approve/reject/cancel and publish side effects.",
        api_routes=("/life/metabolism/tickets",),
        runtime_facade_methods=(
            "life_metabolism_ticket_get",
            "life_metabolism_ticket_list",
            "life_metabolism_ticket_approve",
            "life_metabolism_ticket_reject",
            "life_metabolism_ticket_cancel",
        ),
        contract_modules=(
            "xinyu_bridge_life_metabolism_contract.py",
            "xinyu_bridge_life_metabolism_route_backend.py",
            "xinyu_bridge_metabolism_routes.py",
            "xinyu_bridge_metabolism_ticket_routes.py",
            "xinyu_bridge_metabolism_runner.py",
            "xinyu_bridge_metabolism_publish.py",
        ),
        validation_tests=(
            "tests/test_life_metabolism_contract.py",
            "tests/test_life_metabolism_service.py",
            "tests/test_life_metabolism_route_backend.py",
            "tests/test_bridge_metabolism_routes.py",
            "tests/smoke/life/metabolism_http_smoke.py",
        ),
        process_split_candidate=False,
        process_split_ready=False,
        process_split_gate="Keep local while self-choice policy, desktop visibility, and runtime lifecycle are tightly coupled.",
    ),
    ServiceBoundaryContract(
        service_id="health_diagnostics",
        local_owner="HealthDiagnosticsService",
        owner_layer="api/diagnostics",
        purpose="Expose health, probe, runtime repair status, and digest-safe diagnostics.",
        api_routes=("/health", "/probe", "/turn/current"),
        runtime_facade_methods=("health", "probe", "turn_current"),
        contract_modules=(
            "xinyu_bridge_health_snapshot.py",
            "xinyu_bridge_health_diagnostics_service.py",
            "xinyu_bridge_health_provider_registry.py",
            "xinyu_bridge_health_provider_registry_service.py",
            "xinyu_bridge_health_service_providers.py",
            "xinyu_bridge_health_snapshot_service.py",
            "xinyu_bridge_utility_probe.py",
            "xinyu_bridge_runtime_repair_status_route.py",
            "xinyu_bridge_runtime_repair_status_providers.py",
        ),
        validation_tests=(
            "tests/test_bridge_health_snapshot.py",
            "tests/test_health_diagnostics_preflight_contract.py",
            "tests/test_health_diagnostics_provider_registry_service.py",
            "tests/test_runtime_repair_status_route.py",
            "tests/test_bridge_http_dispatch.py",
            "tests/smoke/bridge/health_diagnostics_rollback_smoke.py",
            "tests/smoke/bridge/health_diagnostics_provider_registry_smoke.py",
            "tests/smoke/bridge/health_diagnostics_provider_registry_service_smoke.py",
        ),
        process_split_candidate=True,
        process_split_ready=True,
        process_split_gate=(
            "Ready for a controlled health_diagnostics process split using provider registry rollback."
        ),
        process_adapter_kind="provider_registry",
    ),
    ServiceBoundaryContract(
        service_id="diagnostic_reports",
        local_owner="DiagnosticReportService",
        owner_layer="observability/local",
        purpose="Own local-only report and canary builders that inspect runtime traces without exposing public routes.",
        api_routes=(),
        runtime_facade_methods=(),
        contract_modules=(
            "xinyu_bridge_local_report_services.py",
            "xinyu_module_ecology_audit.py",
            "xinyu_feedback_consumption_diagnostics.py",
            "xinyu_short_term_recall_diagnostics.py",
            "xinyu_short_term_continuity_canary.py",
            "xinyu_stage11_visual_ingress_diagnostics.py",
            "xinyu_stage11_voice_ingress_diagnostics.py",
            "xinyu_live_loop_report.py",
            "xinyu_v1_canary_readiness.py",
            "xinyu_autonomy_loop_report.py",
            "xinyu_action_openended_audit.py",
        ),
        validation_tests=(
            "tests/test_local_report_services.py",
            "tests/test_module_ecology_audit.py",
            "tests/test_feedback_consumption_diagnostics.py",
            "tests/test_short_term_recall_diagnostics.py",
            "tests/test_short_term_continuity_canary.py",
            "tests/test_stage11_visual_ingress_diagnostics.py",
            "tests/test_stage11_voice_ingress_diagnostics.py",
            "tests/test_live_loop_report.py",
            "tests/test_v1_canary_readiness.py",
            "tests/test_autonomy_loop_report.py",
            "tests/test_action_openended_audit.py",
        ),
        process_split_candidate=False,
        process_split_ready=False,
        process_split_gate=(
            "Diagnostic reports remain local until trace readers, report stores, and privacy gates "
            "have a shared observability service boundary."
        ),
    ),
    ServiceBoundaryContract(
        service_id="memory_governance_reports",
        local_owner="MemoryGovernanceService",
        owner_layer="memory/governance_local",
        purpose=(
            "Own local-only memory review, owner decision, review inbox control, "
            "and Stage8 governance report builders."
        ),
        api_routes=(
            "/review/inbox/command",
            "/review/goldmark/mark_request",
        ),
        runtime_facade_methods=(
            "review_inbox_command",
            "goldmark_mark_request",
        ),
        contract_modules=(
            "xinyu_bridge_local_report_services.py",
            "xinyu_memory_candidate_review_cli.py",
            "xinyu_memory_self_review.py",
            "xinyu_review_inbox.py",
            "xinyu_bridge_utility_review.py",
            "xinyu_bridge_utility_goldmark.py",
            "xinyu_bridge_utility_routes.py",
            "xinyu_goldmark.py",
            "xinyu_memory_health_report.py",
            "xinyu_stage8_memory_review_packet.py",
            "xinyu_stage8_duplicate_consolidation_packet.py",
            "xinyu_stage8_learning_trial_validation_packet.py",
        ),
        validation_tests=(
            "tests/test_local_report_services.py",
            "tests/test_memory_candidate_review_cli.py",
            "tests/test_memory_self_review.py",
            "tests/test_memory_review_inbox_integration.py",
            "tests/smoke/tools/xinyu_review_inbox_smoke.py",
            "tests/test_goldmark_mark.py",
            "tests/test_memory_health_report.py",
            "tests/test_stage8_memory_review_packet.py",
            "tests/test_stage8_duplicate_consolidation_packet.py",
            "tests/test_stage8_learning_trial_validation_packet.py",
        ),
        process_split_candidate=False,
        process_split_ready=False,
        process_split_gate=(
            "Memory governance remains local until candidate review, promotion preview, owner review inbox, "
            "and Stage8 packets share a stable service boundary."
        ),
    ),
    ServiceBoundaryContract(
        service_id="state_persistence",
        local_owner="StateService",
        owner_layer="persistence",
        purpose="Own atomic JSON/text writes, safe local state reads, projections, runtime queues, traces, and protected memory gates.",
        api_routes=(),
        runtime_facade_methods=(),
        contract_modules=(
            "xinyu_bridge_state_persistence_contract.py",
            "xinyu_bridge_state_persistence_service.py",
            "state_service.py",
            "stores/state_service.py",
            "stores/daily_digest_state.py",
            "stores/source_extracts.py",
            "stores/sticker_send_state.py",
            "stores/impulse_soup_state.py",
            "stores/review_state.py",
            "stores/self_action_queue.py",
            "xinyu_action_experience_digest_store.py",
            "xinyu_bridge_stores.py",
            "xinyu_action_feedback_coverage_store.py",
            "xinyu_action_feedback_surface_store.py",
            "xinyu_async_exploration_store.py",
            "xinyu_attention_posture_store.py",
            "xinyu_autonomous_outward_action_store.py",
            "xinyu_autonomous_self_exploration_store.py",
            "xinyu_chat_replay_fixture_exporter_store.py",
            "xinyu_code_awareness_store.py",
            "xinyu_continuity_handoff_store.py",
            "xinyu_early_visible_segment_store.py",
            "xinyu_expression_self_learning_store.py",
            "xinyu_goal_outcome_observer_store.py",
            "xinyu_group_interest_memory_store.py",
            "xinyu_group_shadow_observer_store.py",
            "xinyu_group_social_store.py",
            "xinyu_learning_closed_loop_store.py",
            "xinyu_private_reply_selftest_store.py",
            "xinyu_prompt_pressure_store.py",
            "xinyu_qq_visible_send_shadow_store.py",
            "xinyu_qq_voice_transcript_store.py",
            "xinyu_recent_attachment_context_store.py",
            "xinyu_recent_context_guard_store.py",
            "xinyu_self_action_gateway_store.py",
            "xinyu_self_action_patch_executor_store.py",
            "xinyu_self_chosen_goal_ecology_store.py",
            "xinyu_self_code_approval_store.py",
            "xinyu_self_code_watchdog_store.py",
            "xinyu_self_state_capsule_store.py",
            "xinyu_tts_output_store.py",
            "xinyu_storage_paths.py",
            "xinyu_bridge_runtime_state.py",
            "xinyu_autonomy_journal_store.py",
            "xinyu_private_ecosystem_journal_store.py",
            "xinyu_tool_targets_store.py",
            "xinyu_self_choice_store.py",
            "xinyu_tinykernel_shadow_store.py",
            "xinyu_life_posture_store.py",
            "xinyu_life_month_slots_store.py",
            "xinyu_memory_weights_store.py",
            "xinyu_thought_seeds_store.py",
            "xinyu_sent_reply_index_store.py",
            "xinyu_memory_promotion_store.py",
            "xinyu_memory_candidate_maintenance_store.py",
            "xinyu_uncertainty_pause_store.py",
            "xinyu_proactive_lifecycle_trace_store.py",
            "xinyu_gateway_ack_spool_store.py",
            "xinyu_voice_trial_overlay_store.py",
            "xinyu_voice_calibration_store.py",
            "xinyu_dialogue_rule_trial_overlay_store.py",
            "xinyu_visible_state_hygiene_store.py",
            "xinyu_dialogue_working_memory_store.py",
            "xinyu_short_term_continuity_store.py",
            "xinyu_turn_residue_store.py",
            "xinyu_turn_coherence_store.py",
            "xinyu_stage9_self_state_model_store.py",
            "xinyu_voice_style_observations_store.py",
            "xinyu_voice_style_sampler_store.py",
            "xinyu_perception_importance_store.py",
            "xinyu_short_term_continuity_canary_store.py",
            "xinyu_v1_canary_readiness_store.py",
            "xinyu_short_term_recall_diagnostics_store.py",
            "xinyu_proactive_response_diagnostics_store.py",
            "xinyu_stage8_memory_review_packet_store.py",
            "xinyu_autonomy_loop_report_store.py",
            "xinyu_action_openended_audit_store.py",
            "xinyu_autonomy_canary_report_store.py",
            "xinyu_feedback_consumption_diagnostics_store.py",
            "xinyu_stage11_visual_ingress_diagnostics_store.py",
            "xinyu_stage11_voice_ingress_diagnostics_store.py",
            "xinyu_module_ecology_audit_store.py",
            "xinyu_live_loop_report_store.py",
            "xinyu_memory_health_report_store.py",
            "xinyu_persona_health_report_store.py",
            "xinyu_stage8_duplicate_consolidation_packet_store.py",
            "xinyu_stage8_learning_trial_validation_packet_store.py",
            "xinyu_stage11_multisensory_extension_store.py",
            "xinyu_stage10_proactive_life_loop_store.py",
            "xinyu_qq_reply_integrity_diagnostics_store.py",
            "xinyu_decision_chain_latest_store.py",
            "xinyu_owner_feedback_effects_store.py",
            "xinyu_perception_event_layer_store.py",
            "xinyu_stage12_long_term_evaluation_store.py",
            "xinyu_stage13_self_narrative_store.py",
            "xinyu_watched_sources_store.py",
            "xinyu_turn_route_trace.py",
            "xinyu_turn_route_trace_store.py",
        ),
        validation_tests=(
            "tests/test_state_persistence_contract.py",
            "tests/test_state_persistence_service.py",
            "tests/test_daily_digest_state_store.py",
            "tests/test_source_extracts_store.py",
            "tests/test_sticker_send_state_store.py",
            "tests/test_impulse_soup_state_store.py",
            "tests/test_review_state_store.py",
            "tests/test_self_action_queue_store.py",
            "tests/test_action_experience_digest_store.py",
            "tests/test_action_feedback_coverage_store.py",
            "tests/test_action_feedback_surface_store.py",
            "tests/test_async_exploration_store.py",
            "tests/test_attention_posture_store.py",
            "tests/test_autonomous_outward_action_store.py",
            "tests/test_autonomous_self_exploration_store.py",
            "tests/test_bridge_autonomous_state_store.py",
            "tests/test_bridge_codex_presence_store.py",
            "tests/test_bridge_desktop_proactive_state_store.py",
            "tests/test_bridge_external_plugin_trace_store.py",
            "tests/test_bridge_learning_codex_reports_store.py",
            "tests/test_bridge_learning_sidecars_store.py",
            "tests/test_bridge_proactive_context_state_store.py",
            "tests/test_bridge_promise_followup_state_store.py",
            "tests/test_bridge_renderer_debug_store.py",
            "tests/test_bridge_state_text_store.py",
            "tests/test_chat_replay_fixture_exporter_store.py",
            "tests/test_code_awareness_store.py",
            "tests/test_continuity_handoff_store.py",
            "tests/test_early_visible_segment_store.py",
            "tests/test_expression_self_learning_store.py",
            "tests/test_goal_outcome_observer_store.py",
            "tests/test_group_interest_memory_store.py",
            "tests/test_group_shadow_observer_store.py",
            "tests/test_group_social_store.py",
            "tests/test_learning_closed_loop_store.py",
            "tests/test_private_reply_selftest_store.py",
            "tests/test_prompt_pressure_store.py",
            "tests/test_qq_visible_send_shadow_store.py",
            "tests/test_qq_voice_transcript_store.py",
            "tests/test_recent_attachment_context_store.py",
            "tests/test_recent_context_guard_store.py",
            "tests/test_self_action_gateway_store.py",
            "tests/test_self_action_patch_executor_store.py",
            "tests/test_self_chosen_goal_ecology_store.py",
            "tests/test_self_code_approval_store.py",
            "tests/test_self_code_watchdog_store.py",
            "tests/test_self_state_capsule_store.py",
            "tests/test_tts_output_store.py",
            "tests/test_autonomy_journal_store.py",
            "tests/test_private_ecosystem_journal_store.py",
            "tests/test_bridge_bootstrap_store.py",
            "tests/test_bridge_prompt_context_signature_store.py",
            "tests/test_bridge_observation_reports_store.py",
            "tests/test_bridge_voice_flags_store.py",
            "tests/test_bridge_private_desktop_frame_store.py",
            "tests/test_bridge_private_desktop_status_store.py",
            "tests/test_bridge_desktop_service_status_store.py",
            "tests/test_desktop_self_action_snapshot_payload_store.py",
            "tests/test_tool_targets_store.py",
            "tests/test_learning_ingest_scope_store.py",
            "tests/test_bridge_promise_owner_identity_store.py",
            "tests/test_bridge_cli_env_store.py",
            "tests/test_self_choice_store.py",
            "tests/test_tinykernel_shadow_store.py",
            "tests/test_life_posture_store.py",
            "tests/test_life_month_slots_store.py",
            "tests/test_memory_weights_store.py",
            "tests/test_thought_seeds_store.py",
            "tests/test_sent_reply_index_store.py",
            "tests/test_memory_promotion_store.py",
            "tests/test_memory_candidate_maintenance_store.py",
            "tests/test_uncertainty_pause_store.py",
            "tests/test_proactive_lifecycle_trace_store.py",
            "tests/test_gateway_ack_spool_store.py",
            "tests/test_voice_trial_overlay_store.py",
            "tests/test_voice_calibration_store.py",
            "tests/test_dialogue_rule_trial_overlay_store.py",
            "tests/test_visible_state_hygiene_store.py",
            "tests/test_dialogue_working_memory_store.py",
            "tests/test_short_term_continuity_store.py",
            "tests/test_turn_residue_store.py",
            "tests/test_turn_coherence_store.py",
            "tests/test_stage9_self_state_model_store.py",
            "tests/test_voice_style_observations_store.py",
            "tests/test_voice_style_sampler_store.py",
            "tests/test_perception_importance_store.py",
            "tests/test_short_term_continuity_canary_store.py",
            "tests/test_v1_canary_readiness_store.py",
            "tests/test_short_term_recall_diagnostics_store.py",
            "tests/test_proactive_response_diagnostics_store.py",
            "tests/test_stage8_memory_review_packet_store.py",
            "tests/test_autonomy_loop_report_store.py",
            "tests/test_action_openended_audit_store.py",
            "tests/test_autonomy_canary_report_store.py",
            "tests/test_feedback_consumption_diagnostics_store.py",
            "tests/test_stage11_visual_ingress_diagnostics_store.py",
            "tests/test_stage11_voice_ingress_diagnostics_store.py",
            "tests/test_module_ecology_audit_store.py",
            "tests/test_live_loop_report_store.py",
            "tests/test_memory_health_report_store.py",
            "tests/test_persona_health_report_store.py",
            "tests/test_stage8_duplicate_consolidation_packet_store.py",
            "tests/test_stage8_learning_trial_validation_packet_store.py",
            "tests/test_stage11_multisensory_extension_store.py",
            "tests/test_stage10_proactive_life_loop_store.py",
            "tests/test_qq_reply_integrity_diagnostics_store.py",
            "tests/test_decision_chain_latest_store.py",
            "tests/test_owner_feedback_effects_store.py",
            "tests/test_perception_event_layer_store.py",
            "tests/test_stage12_long_term_evaluation_store.py",
            "tests/test_stage13_self_narrative_store.py",
            "tests/test_watched_sources_store.py",
            "tests/test_turn_route_trace_store.py",
            "tests/smoke/dialogue/integration/resource_boundary_smoke.py",
            "tests/test_runtime_trace_boundary_audit.py",
        ),
        process_split_candidate=False,
        process_split_ready=False,
        process_split_gate="Persistence boundary must consolidate writes locally before any external state service is considered.",
    ),
)


def service_boundary_contracts() -> tuple[ServiceBoundaryContract, ...]:
    return SERVICE_BOUNDARY_CONTRACTS


def service_contract_by_id(service_id: str) -> ServiceBoundaryContract:
    for contract in SERVICE_BOUNDARY_CONTRACTS:
        if contract.service_id == service_id:
            return contract
    raise KeyError(service_id)


def process_split_candidates() -> tuple[ServiceBoundaryContract, ...]:
    return tuple(contract for contract in SERVICE_BOUNDARY_CONTRACTS if contract.process_split_candidate)


def process_split_ready_contracts() -> tuple[ServiceBoundaryContract, ...]:
    return tuple(contract for contract in SERVICE_BOUNDARY_CONTRACTS if contract.process_split_ready)


def validate_service_boundary_contracts(root: Path) -> tuple[str, ...]:
    errors: list[str] = []
    seen_ids: set[str] = set()
    for contract in SERVICE_BOUNDARY_CONTRACTS:
        if contract.service_id in seen_ids:
            errors.append(f"duplicate service_id: {contract.service_id}")
        seen_ids.add(contract.service_id)
        if contract.process_split_ready and not contract.process_split_candidate:
            errors.append(f"{contract.service_id}: ready service is not marked as split candidate")
        if not contract.process_split_gate.strip():
            errors.append(f"{contract.service_id}: missing process split gate")
        for rel in contract.contract_modules:
            if not (root / rel).exists():
                errors.append(f"{contract.service_id}: missing contract module {rel}")
        for rel in contract.validation_tests:
            if not (root / rel).exists():
                errors.append(f"{contract.service_id}: missing validation test {rel}")
    return tuple(errors)
