"""Shared inner-framework manifest for Xinyu.

This keeps layer ordering and deterministic sync targets in one place so
plugins, future writers, and validation scripts can refer to the same model.
"""

from __future__ import annotations

INNER_FRAMEWORK_LAYERS: list[dict[str, object]] = [
    {
        "name": "anchor",
        "files": [
            "memory/self/core.md",
            "memory/self/personality_profile.md",
            "memory/self/mind_loop_policy.md",
            "memory/self/voice_profile_zh.md",
            "memory/self/boundaries.md",
            "memory/context/real_world_anchor_policy.md",
            "memory/context/real_life_input_adapter_policy.md",
            "memory/context/capability_zones_state.md",
            "memory/archive/retention_model.md",
            "memory/context/exploration_policy.md",
            "memory/reflection/reflection_policy.md",
            "memory/dreams/dream_policy.md",
        ],
        "update_mode": "rare",
    },
    {
        "name": "time_continuity",
        "files": [
            "memory/context/time_anchor.md",
            "memory/context/continuity_index.md",
            "memory/context/automation_policy.md",
            "memory/context/automation_state.md",
            "memory/context/runtime_bridge_state.md",
            "memory/context/inner_cycle_state.md",
            "memory/context/recent_context.md",
            "memory/context/runtime_rhythm.md",
            "memory/context/maintenance_plan.md",
            "memory/context/maintenance_targets.md",
            "memory/context/maintenance_recommendations.md",
            "memory/context/maintenance_dispatch_state.md",
            "memory/context/initiative_policy.md",
            "memory/context/initiative_state.md",
            "memory/context/proactive_presence_state.md",
            "memory/context/inner_sync_state.md",
            "memory/context/real_life_input_events.md",
            "memory/context/real_life_input_adapter_state.md",
        ],
        "update_mode": "every_meaningful_turn",
    },
    {
        "name": "immediate_feeling",
        "files": [
            "memory/emotions/taxonomy.md",
            "memory/emotions/current_state.md",
            "memory/emotions/event_log.md",
            "memory/context/unfinished_experiences.md",
        ],
        "update_mode": "every_meaningful_turn",
    },
    {
        "name": "relationship",
        "files": [
            "memory/people/owner.md",
            "memory/relationships/index.md",
            "memory/relationships/owner_patterns.md",
            "memory/relationships/vector_model.md",
        ],
        "update_mode": "every_meaningful_turn",
    },
    {
        "name": "self_narrative",
        "files": [
            "memory/self/narrative.md",
            "memory/self/mind_loop_state.md",
            "memory/self/voice_calibration_log.md",
            "memory/self/personality_change_state.md",
            "memory/self/ai_self_iteration_state.md",
            "memory/self/ai_self_iteration_review_state.md",
        ],
        "update_mode": "when_meaning_changes",
    },
    {
        "name": "question_exploration",
        "files": [
            "memory/context/active_questions.md",
            "memory/context/question_pipeline_state.md",
            "memory/context/question_states.md",
            "memory/context/exploration_queue.md",
            "memory/context/social_inquiry_candidates.md",
            "memory/knowledge/general.md",
            "memory/knowledge/ai_domain.md",
            "memory/knowledge/social_inquiry_policy.md",
            "memory/knowledge/social_inquiry_policy_state.md",
            "memory/knowledge/social_inquiry_answers.md",
            "memory/knowledge/source_notes.md",
            "memory/knowledge/source_materials.md",
            "memory/knowledge/source_requests.md",
            "memory/knowledge/source_gate_state.md",
            "memory/knowledge/source_reliability_state.md",
            "memory/knowledge/source_integration_gate_state.md",
            "memory/knowledge/source_request_planner_state.md",
            "memory/knowledge/source_search_results.md",
            "memory/knowledge/source_search_resolver_state.md",
            "memory/knowledge/autonomous_search_activation_state.md",
            "memory/knowledge/research_loop_dry_run_state.md",
            "memory/knowledge/source_search_provider_state.md",
            "memory/knowledge/search_result_gate_state.md",
            "memory/knowledge/outward_source_state.md",
            "memory/knowledge/source_comparison_state.md",
            "memory/knowledge/learner_integration_state.md",
            "memory/knowledge/learning_quality_state.md",
            "memory/knowledge/source_registry.md",
            "memory/knowledge/integration_policy.md",
        ],
        "update_mode": "conditional",
    },
    {
        "name": "slow_reprocessing",
        "files": [
            "memory/reflection/reflection_queue.md",
            "memory/reflection/reprocessing_state.md",
            "memory/reflection/consolidation_state.md",
            "memory/reflection/reflection_output_state.md",
            "memory/reflection/reflection_log.md",
            "memory/reflection/growth_log.md",
            "memory/dreams/dream_seeds.md",
            "memory/dreams/dream_output_state.md",
            "memory/dreams/dream_weight_state.md",
            "memory/dreams/dream_log.md",
            "memory/archive/archive_queue.md",
            "memory/archive/long_term_memory_gate_state.md",
            "memory/archive/retention_gate_state.md",
            "memory/archive/archive_output_state.md",
            "memory/archive/archive_commit_state.md",
            "memory/archive/compressed.md",
            "memory/archive/dormant.md",
            "memory/archive/archive_policy.md",
        ],
        "update_mode": "queued",
    },
]

DETERMINISTIC_SYNC_ORDER: list[str] = [
    "time_anchor",
    "recent_context",
    "current_state",
    "owner_profile",
    "relationship_index",
    "continuity_index",
    "owner_patterns",
    "self_narrative",
    "reflection_queue",
    "dream_seeds",
    "archive_queue",
    "maintenance_targets",
    "inner_sync_state",
    "unfinished_experiences",
    "active_questions",
    "initiative_state",
    "question_states",
    "exploration_queue",
]

SYNC_LAYER_NAMES: list[str] = [
    "anchor/time",
    "immediate_feeling",
    "relationship",
    "continuity",
    "self_narrative",
    "question_pipeline",
    "initiative_loop",
    "reflection_queue",
    "dream_seeds",
    "archive_queue",
    "maintenance_targets",
    "reflection_output",
    "dream_output",
    "source_gate",
    "source_reliability",
    "source_integration_gate",
    "source_request_planner",
    "source_search_resolver",
    "autonomous_search_activation",
    "source_search_provider",
    "search_result_gate",
    "outward_source",
    "source_comparison",
    "learner_integration",
    "learning_quality",
    "ai_self_iteration_gate",
    "consolidation",
    "long_term_memory_gate",
    "retention_gate",
    "archive_output",
    "archive_commit",
    "personality_growth_gate",
]
